<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your AI Itinerary - Tourex</title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>

<body class="bg-background-soft font-sans antialiased text-primary">
    <!-- Mini Navbar -->
    <header class="bg-white border-b border-gray-100 sticky top-0 z-50">
        <div class="max-w-7xl mx-auto px-8 py-4 flex justify-between items-center">
            <a href="{{ route('home') }}" class="text-2xl font-bold tracking-tight">tourex</a>
            <div class="flex items-center gap-4">
                <span class="text-sm font-medium text-gray-500">AI Powered Planner</span>
            </div>
        </div>
    </header>

    <main class="max-w-4xl mx-auto px-8 py-16">

        {{-- Success Flash Message --}}
        @if(session('success'))
            <div id="flash-message"
                class="mb-8 flex items-center gap-3 bg-green-50 border border-green-200 text-green-800 px-6 py-4 rounded-2xl shadow-sm">
                <span class="text-xl">✨</span>
                <p class="font-medium">{{ session('success') }}</p>
                <button onclick="document.getElementById('flash-message').remove()"
                    class="ml-auto text-green-500 hover:text-green-700 transition-colors text-lg leading-none">&times;</button>
            </div>
        @endif

        <div class="bg-white rounded-[3rem] shadow-sm overflow-hidden border border-gray-50">
            <div class="bg-primary p-12 text-white">
                <div class="flex flex-col md:flex-row justify-between items-start md:items-center gap-8">
                    <div>
                        <h1 class="text-4xl font-bold mb-2">Trip to {{ $itinerary->destination }}</h1>
                        <p class="opacity-70 flex items-center gap-2">
                            <i data-lucide="calendar" class="w-4 h-4"></i>
                            {{ $itinerary->days }} Days Adventure • Budget: ₹{{ number_format($itinerary->budget) }}
                        </p>
                    </div>
                    <div class="bg-white/10 backdrop-blur-md p-6 rounded-4xl border border-white/10">
                        <p class="text-[10px] font-bold uppercase tracking-widest opacity-50 mb-1">Generated by</p>
                        <p class="font-bold flex items-center gap-2">
                            <i data-lucide="sparkles" class="w-4 h-4"></i>
                            Tourex AI Assistant
                        </p>
                    </div>
                </div>
            </div>

            <div class="p-12">
                <div id="itinerary-content" class="prose prose-lg prose-slate max-w-none">
                    <!-- Markdown Content will be rendered here -->
                    <div class="hidden" id="raw-content">{{ $itinerary->generated_plan }}</div>
                </div>

                <div
                    class="mt-16 pt-12 border-t border-gray-100 flex flex-col md:flex-row justify-between items-center gap-8">
                    <div class="space-y-1">
                        <h4 class="font-bold text-xl">Love this plan?</h4>
                        <p class="text-gray-400">You can save this itinerary to your profile or book flights and hotels
                            now.</p>
                    </div>
                    <div class="flex gap-4 flex-wrap justify-center">
                        {{-- Regenerate Button --}}
                        <form method="POST" action="{{ route('ai.regenerate', $itinerary->id) }}" id="regenerate-form">
                            @csrf
                            <button type="submit" id="regenerate-btn"
                                class="px-8 py-4 border border-gray-200 rounded-2xl font-bold hover:bg-amber-50 hover:border-amber-300 hover:text-amber-700 transition-all flex items-center gap-2 group">
                                <i data-lucide="refresh-cw"
                                    class="w-4 h-4 group-hover:rotate-180 transition-transform duration-500"></i>
                                <span id="regenerate-label">Try a Different Plan</span>
                            </button>
                        </form>

                        <button
                            class="px-8 py-4 border border-gray-200 rounded-2xl font-bold hover:bg-gray-50 transition-all">
                            Save Plan
                        </button>
                        <a href="{{ route('home') }}"
                            class="px-8 py-4 bg-primary text-white rounded-2xl font-bold shadow-xl shadow-primary/20 hover:bg-black transition-all">
                            Book This Trip
                        </a>
                    </div>
                </div>

                {{-- Regenerate hint text --}}
                <p class="text-center text-xs text-gray-400 mt-6">
                    <i data-lucide="info" class="w-3 h-3 inline-block mr-1"></i>
                    Not happy with this itinerary? Click <strong>Try a Different Plan</strong> to generate a fresh one
                    with different places and routes.
                </p>
            </div>
        </div>
    </main>

    <script src="https://unpkg.com/lucide@latest"></script>
    <script>
        lucide.createIcons();

        // Render Markdown
        const rawContent = document.getElementById('raw-content').textContent;
        document.getElementById('itinerary-content').innerHTML = marked.parse(rawContent);

        // Regenerate button loading state
        const form = document.getElementById('regenerate-form');
        const btn = document.getElementById('regenerate-btn');
        const label = document.getElementById('regenerate-label');

        form.addEventListener('submit', function () {
            btn.disabled = true;
            btn.classList.add('opacity-70', 'cursor-not-allowed');
            label.textContent = 'Generating new plan…';

            // Spin the icon continuously while loading
            const icon = btn.querySelector('[data-lucide="refresh-cw"]');
            if (icon) {
                icon.style.animation = 'spin 1s linear infinite';
            }
        });
    </script>

    <style>
        @keyframes spin {
            from {
                transform: rotate(0deg);
            }

            to {
                transform: rotate(360deg);
            }
        }

        .prose h2 {
            font-weight: 800;
            color: #1A1A1A;
            margin-top: 2rem;
            margin-bottom: 1rem;
            font-size: 1.875rem;
        }

        .prose h3 {
            font-weight: 700;
            color: #1A1A1A;
            margin-top: 1.5rem;
            margin-bottom: 0.75rem;
            font-size: 1.5rem;
        }

        .prose p {
            color: #4A4A4A;
            line-height: 1.8;
            margin-bottom: 1.25rem;
        }

        .prose ul {
            list-style-type: disc;
            padding-left: 1.5rem;
            margin-bottom: 1.25rem;
        }

        .prose li {
            color: #4A4A4A;
            margin-bottom: 0.5rem;
        }

        .prose strong {
            color: #1A1A1A;
            font-weight: 700;
        }
    </style>
</body>

</html>